const express = require('express')
const router = express.Router()
const genrecontroller = require('../controller/genrecontroller')
const filmcontroller = require('../controller/filmcontroller')
const descriptioncontroller = require('../controller/descriptioncontroller')
const descriptionfavoritcontroller = require('../controller/descriptionfavoritcontroller')
const favoritcontroller = require('../controller/favoritcontroller')
const genreseriescontroller = require('../controller/genreseriescontroller')
const seriescontroller = require('../controller/seriescontroller')
const descriptionseriescontroller = require('../controller/descriptionseriescontroller')
const episodecontroller = require('../controller/episodecontroller')
const genremusiccontroller = require('../controller/genremusiccontroller')
const musiccontroller = require('../controller/musiccontroller')
const jenisenterteinmentcontroller = require('../controller/jenisenterteinment')
const enterteinmentcontroller = require('../controller/enterteinmentcontroller')
const jeniscontroller = require('../controller/jeniscontroller')
const newscontroller = require('../controller/newscontroller')
const genreanimecontroller = require('../controller/genreanimecontroller')
const animecontroller = require('../controller/animecontroller')
const descriptionanimecontroller = require('../controller/descriptionanimecontroller')
const episodeanimecontroller = require('../controller/episodeanimecontroller')
const sportcontroller = require('../controller/sportcontroller')
const terbaikcontroller = require('../controller/terbaikcontroller')


router.get('/genre',genrecontroller.index)
router.get('/genre/:id',genrecontroller.show)
router.post('/genre',genrecontroller.store)
router.put('/genre/:id',genrecontroller.update)
router.delete('/genre/:id',genrecontroller.destroy)
router.get('/film',filmcontroller.index)
router.get('/film/:id',filmcontroller.show)
router.get('/filmw',filmcontroller.show1)
router.post('/film',filmcontroller.store)
router.put('/film/:id',filmcontroller.update)
router.delete('/film/:id',filmcontroller.destroy)
router.get('/description',descriptioncontroller.index)
router.get('/description/:id',descriptioncontroller.show)
router.post('/description',descriptioncontroller.store)
router.put('/description/:id',descriptioncontroller.update)
router.delete('/description/:id',descriptioncontroller.destroy)
router.get('/descriptionfavorit',descriptionfavoritcontroller.index)
router.get('/descriptionfavorit/:id',descriptionfavoritcontroller.show)
router.post('/descriptionfavorit',descriptionfavoritcontroller.store)
router.put('/descriptionfavorit/:id',descriptionfavoritcontroller.update)
router.delete('/descriptionfavorit/:id',descriptionfavoritcontroller.destroy)
router.get('/favorit',favoritcontroller.index)
router.get('/favorit/:id',favoritcontroller.show)
router.post('/favorit',favoritcontroller.store)
router.put('/favorit/:id',favoritcontroller.update)
router.delete('/favorit/:id',favoritcontroller.destroy)
router.get('/genreseries',genreseriescontroller.index)
router.get('/genreseries/:id',genreseriescontroller.show)
router.post('/genreseries',genreseriescontroller.store)
router.put('/genreseries/:id',genreseriescontroller.update)
router.delete('/genreseries/:id',genreseriescontroller.destroy)
router.get('/series',seriescontroller.index)
router.get('/series/:id',seriescontroller.show)
router.post('/series',seriescontroller.store)
router.put('/series/:id',seriescontroller.update)
router.delete('/series/:id',seriescontroller.destroy)
router.get('/descriptionseries',descriptionseriescontroller.index)
router.get('/descriptionseries/:id',descriptionseriescontroller.show)
router.post('/descriptionseries',descriptionseriescontroller.store)
router.put('/descriptionseries/:id',descriptionseriescontroller.update)
router.delete('/descriptionseries/:id',descriptionseriescontroller.destroy)
router.get('/episode',episodecontroller.index)
router.get('/episode/:id',episodecontroller.show)
router.get('/episode1/:series_id',episodecontroller.index1)
router.get('/episode1/:series_id/:judul',episodecontroller.searchseries1)
router.post('/episode',episodecontroller.store)
router.put('/episode/:id',episodecontroller.update)
router.delete('/episode/:id',episodecontroller.destroy)
router.get('/genremusic',genremusiccontroller.index)
router.get('/genremusic/:id',genremusiccontroller.show)
router.post('/genremusic',genremusiccontroller.store)
router.put('/genremusic/:id',genremusiccontroller.update)
router.delete('/genremusic/:id',genremusiccontroller.destroy)
router.get('/music',musiccontroller.index)
router.get('/music/:id',musiccontroller.show)
router.post('/music',musiccontroller.store)
router.put('/music/:id',musiccontroller.update)
router.delete('/music/:id',musiccontroller.destroy)
router.get('/jensienterteinment',jenisenterteinmentcontroller.index)
router.get('/jensienterteinment/:id',jenisenterteinmentcontroller.show)
router.post('/jensienterteinment',jenisenterteinmentcontroller.store)
router.put('/jensienterteinment/:id',jenisenterteinmentcontroller.update)
router.delete('/jensienterteinment/:id',jenisenterteinmentcontroller.destroy)
router.get('/enterteinment',enterteinmentcontroller.index)
router.get('/enterteinment/:id',enterteinmentcontroller.show)
router.post('/enterteinment',enterteinmentcontroller.store)
router.put('/enterteinment/:id',enterteinmentcontroller.update)
router.delete('/enterteinment/:id',enterteinmentcontroller.destroy)
router.get('/jenis',jeniscontroller.index)
router.get('/jenis/:id',jeniscontroller.show)
router.post('/jenis',jeniscontroller.store)
router.put('/jenis/:id',jeniscontroller.update)
router.delete('/jenis/:id',jeniscontroller.destroy)
router.get('/news',newscontroller.index)
router.get('/news/:id',newscontroller.show)
router.post('/news',newscontroller.store)
router.put('/news/:id',newscontroller.update)
router.delete('/news/:id',newscontroller.destroy)
router.get('/genreanime',genreanimecontroller.index)
router.get('/genreanime/:id',genreanimecontroller.show)
router.post('/genreanime',genreanimecontroller.store)
router.put('/genreanime/:id',genreanimecontroller.update)
router.delete('/genreanime/:id',genreanimecontroller.destroy)
router.get('/anime',animecontroller.index)
router.get('/anime/:id',animecontroller.show)
router.post('/anime',animecontroller.store)
router.put('/anime/:id',animecontroller.update)
router.delete('/anime/:id',animecontroller.destroy)
router.get('/descritionanime',descriptionanimecontroller.index)
router.get('/descritionanime/:id',descriptionanimecontroller.show)
router.post('/descritionanime',descriptionanimecontroller.store)
router.put('/descritionanime/:id',descriptionanimecontroller.update)
router.delete('/descritionanime/:id',descriptionanimecontroller.destroy)
router.get('/episodeanime',episodeanimecontroller.index)
router.get('/episodeanime/:id',episodeanimecontroller.show)
router.post('/episodeanime',episodeanimecontroller.store)
router.put('/episodeanime/:id',episodeanimecontroller.update)
router.delete('/episodeanime/:id',episodeanimecontroller.destroy)
router.get('/sport',sportcontroller.index)
router.get('/sport/:id',sportcontroller.show)
router.post('/sport',sportcontroller.store)
router.put('/sport/:id',sportcontroller.update)
router.delete('/sport/:id',sportcontroller.destroy)
router.get('/sport1',sportcontroller.footbal)
router.get('/sport2',sportcontroller.volley)
router.get('/sport3',sportcontroller.mpl)
router.get('/sport4',sportcontroller.liga1)
router.get('/sportfav',sportcontroller.fav)
router.get('/movie1',filmcontroller.drama)
router.get('/movie2',filmcontroller.komedi)
router.get('/movie3',filmcontroller.action)
router.get('/movie4',filmcontroller.horror)
router.get('/moviefav',filmcontroller.fav)
router.get('/series1',seriescontroller.kriminal)
router.get('/series2',seriescontroller.medicaldrama)
router.get('/series3',seriescontroller.historicaldrama)
router.get('/series4',seriescontroller.romancecomedy)
router.get('/seriesfav',seriescontroller.fav)
router.get('/anime1',animecontroller.adventure)
router.get('/anime2',animecontroller.Sword)
router.get('/anime3',animecontroller.demon)
router.get('/anime4',animecontroller.Shounen)
router.get('/animefav',animecontroller.fav)
router.get('/terbaikmov',terbaikcontroller.movie)
router.get('/terbaikser',terbaikcontroller.series)
router.get('/terbaikani',terbaikcontroller.anime)
router.get('/searchfilm/:search',terbaikcontroller.searchmovie)
router.get('/searchseries/:search',terbaikcontroller.searchseries)
router.get('/searchanime/:search',terbaikcontroller.searchanime)

module.exports = router